/*
 * Copyright (c) 2013 
 * ==================================
 * 
 *
 * This is part of an item on themeforest
 * You can check out the screenshots and purchase it on themeforest:
 * http://rxa.li/tour
 * 
 * 
 * ===========================================
 * original filename: jTour.min.js
 * filesize: 26646 Bytes
 * last modified: Tue, 29 Jan 2013 14:34:18 +0100
 *
 */
window.jTour=function(k,P){function Q(b){switch(b.keyCode){case 37:"keyup"==b.type&&0<d?H():b.preventDefault();break;case 39:"keyup"==b.type?w():b.preventDefault();break;case 38:"keyup"==b.type?t(0.25):b.preventDefault();break;case 40:"keyup"==b.type?t(-0.25):b.preventDefault();break;case 32:manualskip=!0;"keyup"==b.type?A(!0):b.preventDefault();break;case 27:"keyup"==b.type?E():b.preventDefault()}}function F(b){b||(b=d);I=I||$(window).scrollTop();J=J||$(window).scrollLeft();u.show().fadeIn(function(){c.pauseOnHover&&
e.bind({"mouseenter.jTour":A,"mouseleave.jTour":B});c.keyboardNav&&$(document).bind({"keyup.jTour":Q,"keydown.jTour":Q});x=!1;d=b;c.onStart.call(h,d);K(b)});c.showControls&&(p.find(".play").hide(),p.find(".pause").show())}function E(){busy||(clearTimeout(v),r.clearQueue().stop(),u.hide(),c.pauseOnHover&&e.unbind(".jTour"),c.keyboardNav&&$(document).unbind(".jTour"),c.scrollBack?L(J,I,c.scrollDuration,function(){c.onStop.call(h,d)}):c.onStop.call(h,d),j&&j.exposeElement&&j.exposeElement.css(j.exposeElement.data("jTour")).removeData("jTour").removeClass(m+
"exposed"),R(),d=0,c.showControls&&(p.find(".play").show(),p.find(".pause").hide()))}function A(b,a){if(x){if(!0===b){manualskip=!manualskip;B();return}if(!manualskip)return}!1!==a&&c.onPause.call(h,d);clearTimeout(v);r.clearQueue().stop();c.showControls&&manualskip&&(p.find(".play").show(),p.find(".pause").hide());x=!0}function B(b){if(x&&!manualskip){!1!==b&&c.onPlay.call(h,d);clearTimeout(v);b=r.width()/(C.width()/100)/100;var a=k[d].live||S.live,a=a-a*b;r.clearQueue().stop().animate({width:"100%"},
{duration:a*(1/c.speed),easing:"linear",step:G,complete:w});c.showControls&&(p.find(".play").hide(),p.find(".pause").show());x=!1}}function w(){if(!busy){s&&k[d].steps&&(k[d].onStep&&k[d].onStep.call(h,j,100),$.each(s,function(b,a){k[d].steps[s[b]].call(h,j,a)}),s=null);
if(k[d].goTo)return window.location=k[d].goTo+"#jTour="+(d+1),setTimeout(function(){location.reload()},1E3),!1;if(k[d].showTab)k[d].showTab.click();
d+1<M?(clearTimeout(v),r.clearQueue().stop(),K(++d)):(E(),c.onFinish.call(h,d))}}function H(){!busy&&0<d&&(clearTimeout(v),
r.clearQueue().stop(),K(--d))}function K(b){var a=$.extend({},S,k[b]),n=a.element=a.element?"string"==typeof a.element?$(a.element):a.element:0;if(n.length){if("auto"===a.live){var d=$("<div>").html(a.html).text().length;a.live=k[b].live=Math.max(2500,2500*Math.log(d/10)+1E3)}a.live=Math.abs(a.live);a.isArea="area"==a.element[0].nodeName.toLowerCase();j?j.onBeforeHide.call(h,j.element):(a.delayOut=0,a.animationOut="hide");busy=!0;e[a.animationOut](a.delayOut,function(){e.css({left:0,top:0,"min-width":0});
j&&j.onHide.call(h,j.element);v=setTimeout(function(){var g,d,q,k,f;C.html(a.html);c.onChange.call(h,b);if(n[0]===y[0])g=N*z,d=O*z/2-e.outerHeight()/2,k=q=0;else if(a.isArea){k=n[0].coords.split(",");g=a.exposeElement=$("img[usemap=#"+n.parent().attr("name")+"]");var l=g.offset(),W=parseInt(g.css("paddingTop"),10);q=parseInt(g.css("paddingLeft"),10);var t=parseInt(g.css("borderTopWidth"),10),v=parseInt(g.css("borderLeftWidth"),10);g=k[2]-k[0];d=k[3]-k[1];q=parseInt(k[0],10)+l.left+q+v;k=parseInt(k[1],
10)+l.top+W+t}else g=n.outerWidth(),d=n.outerHeight(),q=n.offset().left,k=n.offset().top;f={left:q,top:k};l={x:0,y:0};switch(a.position){case "ne":isNaN(a.offset)||(a.offset={x:0,y:a.offset});f.top-=e.outerHeight()+a.offset.y;f.left=q+g-e.outerWidth()+a.offset.x;l.x=g/2-+e.outerWidth()/2+a.offset.x;l.y=-d/2-e.outerHeight()/2-a.offset.y;break;case "nw":isNaN(a.offset)||(a.offset={x:0,y:a.offset});f.top-=e.outerHeight()+a.offset.y;f.left=q-a.offset.x;l.x=-g/2+e.outerWidth()/2-a.offset.x;l.y=-d/2-e.outerHeight()/
2-a.offset.y;break;case "n":isNaN(a.offset)||(a.offset={x:0,y:a.offset});f.top-=e.outerHeight()+a.offset.y;f.left+=(g-e.outerWidth())/2+a.offset.x;l.x=a.offset.x;l.y=-d/2-e.outerHeight()/2-a.offset.y;break;case "se":isNaN(a.offset)||(a.offset={x:0,y:a.offset});f.top+=d+a.offset.y;f.left=q+g-e.outerWidth()+a.offset.x;l.x=g/2-e.outerWidth()/2+a.offset.x;l.y=d/2+e.outerHeight()/2+a.offset.y;break;case "sw":isNaN(a.offset)||(a.offset={x:0,y:a.offset});f.top+=d+a.offset.y;f.left=q-a.offset.x;l.x=-g/2+
e.outerWidth()/2-a.offset.x;l.y=d/2+e.outerHeight()/2+a.offset.y;break;case "s":isNaN(a.offset)||(a.offset={x:0,y:a.offset});f.top+=d+a.offset.y;f.left+=(g-e.outerWidth())/2+a.offset.x;l.x=a.offset.x;l.y=d/2+e.outerHeight()/2+a.offset.y;break;case "w":isNaN(a.offset)||(a.offset={x:a.offset,y:0});f.top-=e.outerHeight()/2-d/2-a.offset.y;f.left-=e.outerWidth()+a.offset.x;l.x=-g/2+e.outerWidth()/2-a.offset.x;l.y=-a.offset.y;break;case "e":isNaN(a.offset)||(a.offset={x:a.offset,y:0});f.top-=e.outerHeight()/
2-d/2-a.offset.y;f.left+=g+a.offset.x;l.x=g/2-e.outerWidth()/2+a.offset.x;l.y=-a.offset.y;break;case "c":isNaN(a.offset)||(a.offset={x:0,y:a.offset}),f.top-=e.outerHeight()/2-d/2-a.offset.y,f.left+=(g-e.outerWidth())/2+a.offset.x,l.x=a.offset.x,l.y=a.offset.y}scrolltopos={x:Math.max(0,q-(N*z/2-g/2)+l.x),y:Math.max(0,k-(O*z/2-d/2)+l.y)};j&&(j.exposeElement&&!a.isArea)&&j.exposeElement.css(j.exposeElement.data("jTour")).removeData("jTour").removeClass(m+"exposed");L(scrolltopos.x,scrolltopos.y,c.scrollDuration,
function(){T.removeAttr("class").addClass(m+"arrow "+a.position);a.steps?(s=[],$.each(a.steps,function(a){s.push(a)}),G=function(b){a.onStep.call(h,n,b);var c=s.length;if(c)for(var d=0;d<c;d++)b>=s[d]&&(a.steps[s[d]].call(h,n),s.shift())}):G=function(b){a.onStep.call(h,n,b)};c.showControls&&(0==b?p.find("a.prev").hide():b==M-1?p.find("a.next").hide():p.find("a.next, a.prev").show());a.onBeforeShow.call(h,n);r.clearQueue().stop().css({width:$.browser.opera?"1%":"0%"});f["min-width"]=e.width();if(a.expose&&
n!=y){var d={position:n.css("position"),zIndex:n.css("zIndex")},g={position:"relative",zIndex:X+1};a.exposeElement=a.exposeElement||n;"object"===typeof a.expose&&$.each(a.expose,function(a,b){d[a]=n.css(a);g[a]=b});a.exposeElement.data("jTour",d).css(g).addClass(m+"exposed")}j?j.overlayOpacity!=a.overlayOpacity&&u.fadeTo(2*a.delayIn,a.overlayOpacity):u.css({opacity:a.overlayOpacity});e.css(f).attr("class",U+" step-"+b)[a.animationIn](a.delayIn,function(){busy=!1;a.onShow.call(h,n);j=a;c.autoplay&&
!x&&(manualskip=!1,r.stop().animate({width:"100%"},{duration:a.live*(1/c.speed),easing:"linear",step:G,complete:w}))})})},a.wait)})}else console&&n&&console.log('Element $("'+n.selector+"\") doesn't exist!"),M--,w()}function R(){j&&(j.onBeforeHide.call(h,j.element),r.clearQueue().stop(),e.stop(),e[j.animationOut](j.delayOut,function(){C.empty();j.onHide.call(h,j.element);j=null}))}function t(b){c.speed=Math.max(0.1,c.speed+b);busy||(A(null,!1),B(!1))}function V(b,a,c,d){"object"==typeof b&&(d=$.isFunction(a)?
a:$.isFunction(c)?c:!1,c=!isNaN(a)?a:0,a=b.offset().top,b=b.offset().left);$.isFunction(c)&&(d=c,c=!1);var g={};null!=b&&(g.left=b);null!=a&&(g.top=a);e.animate(g,{duration:!1===c?0:c,complete:d&&function(){d.call(h)}})}function L(b,a,d,e){y.scrollTop()==a&&y.scrollLeft()==b&&(d=1);var g={};$.each(c.axis,function(c,d){g[Y[d]]="x"==d?b:a});y.animate(g,{duration:d||c.scrollDuration,complete:e&&function(){e.call(h)},queue:!0,easing:c.easing})}if(this===window)return new jTour(k,P);if("function"!==typeof jQuery||
171>jQuery.fn.jquery.replace(/\./g,""))return alert("jQuery >=1.7.1 is required for jTour!"),!1;$.isArray(k)||$.error("tourdata must be a valid array");var e,C,r,T,p,u,m="jTour_",y=$.browser.webkit?$("body"):$("html"),d=0,j,M=k.length,v,s,G,x=manualskip=busy=!1,I,J,N,O,X=2E4,z=2.5,U,Y={x:"scrollLeft",y:"scrollTop"},D={speed:1,axis:"xy",autostart:!1,autoplay:!0,pauseOnHover:!0,keyboardNav:!0,showProgress:!0,showControls:!0,scrollBack:!1,scrollDuration:300,easing:"swing",onStart:function(){},onStop:function(){},
onPause:function(){},onPlay:function(){},onChange:function(){},onFinish:function(){},position:"c",live:"auto",offset:0,wait:0,expose:!1,overlayOpacity:0.2,delayIn:200,delayOut:100,animationIn:"fadeIn",animationOut:"fadeOut",onBeforeShow:function(){},onShow:function(){},onBeforeHide:function(){},onHide:function(){},onStep:function(){}};"boolean"!=typeof rx&&(D={});var c=$.extend({},D,P),S={position:c.position,live:c.live,offset:c.offset,wait:c.wait,expose:c.expose,overlayOpacity:c.overlayOpacity,delayIn:c.delayIn,
delayOut:c.delayOut,animationIn:c.animationIn,animationOut:c.animationOut,onBeforeShow:c.onBeforeShow,onShow:c.onShow,onBeforeHide:c.onBeforeHide,onHide:c.onHide,onStep:c.onStep,element:y,goTo:null},h={start:function(b){F(b)},restart:function(b){R();d=b||0;F(b)},pause:function(b){manualskip=!0;A(b)},play:function(){manualskip=!1;B()},stop:function(){E()},next:function(){w()},prev:function(){H()},faster:function(b){t(b||0.25)},slower:function(b){t(b||-0.25)},moveTo:function(b,a,c,d){V(b,a,c,d)},offset:function(b,
a,c,d){V("+="+b,"+="+a,c,d)},scroll:function(b,a,c,d){L(b,a,c,d)}};h.box=h.content=h.overlay=null;h.tourdata=k;a:{e=$("<div/>",{"class":m+"box"}).hide().appendTo("body");T=$("<div/>",{"class":m+"arrow"}).appendTo(e);C=$("<div/>",{"class":m+"content"}).appendTo(e);$("<div/>",{"class":m+"progress"}).html('<div class="'+m+'progress_bar"></div>').appendTo(e);r=e.find("."+m+"progress_bar");c.showControls&&(p=$("<ul/>",{"class":m+"nav"}).html('<li><a class="'+m+'nav_btn prev" title="previous" data-role="prev">&nbsp;</a></li><li><a class="'+
m+'nav_btn play" title="play" data-role="play">&nbsp;</a></li><li><a class="'+m+'nav_btn pause" title="pause" data-role="pause">&nbsp;</a></li><li><a class="'+m+'nav_btn stop" title="stop" data-role="stop">&nbsp;</a></li><li><a class="'+m+'nav_btn next" title="next" data-role="next">&nbsp;</a></li><li><a class="'+m+'nav_btn slower" title="slower" data-role="slower">&nbsp;</a></li><li><a class="'+m+'nav_btn faster" title="faster" data-role="faster">&nbsp;</a></li>').appendTo(e).delegate("a","click.jTour",
function(){manualskip=!0;switch($(this).data("role")){case "next":w();break;case "prev":H();break;case "slower":manualskip=!1;t(-0.25);break;case "faster":manualskip=!1;t(0.25);break;case "pause":A();break;case "play":manualskip=!1;B();e.trigger("mouseleave");break;case "stop":E()}}),e.addClass("has-controls"));u=$("<div/>",{"class":m+"overlay"}).css("opacity",c.overlayOpacity).hide();c.showProgress||e.find("."+m+"progress").hide();!1!==c.overlayOpacity?u.appendTo("body").css("height",$(document).height()):
u.remove();U=e.attr("class");$(window).unbind("resize.jTour").bind("resize.jTour",function(){N=(window.innerWidth||document.documentElement.clientWidth)/z;O=(window.innerHeight||document.documentElement.clientHeight)/z}).resize();h.box=e;h.content=C;h.overlay=u;c.axis=c.axis.split("");if(location.hash&&(D=location.hash.split("="),D[0].match(/jTour/))){location.hash="";F(parseInt(D[1],10));break a}c.autostart&&F()}return h};
